# Generated by Django 6.0.5 on 2026-06-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('department', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
